# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20180109_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='fans',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='income',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
